Added recipe for xarray rolling and dask chunking on aus2200 output
ACCESS-Community-Hub/atmosphere-cookbook pull request #18
Opened 2024-12-05 12:18 UTC by andrewbrown31

2024-12-09 02:55 UTC, navidcy commented
@andrewbrown31, does this PR closes #17? If so, can you either edit the first post of this PR to say `closes #17` or use the "Development" section on the right to link this PR with the issue?

2024-12-09 02:56 UTC, navidcy commented
I'll review the PR. But for future, a good idea is to suggest a few reviewers so that they get notified. Otherwise people might not notice your PR.

2024-12-09 03:22 UTC, andrewbrown31 commented
Thanks Navid. For memory, I don't think I couldn't assign, suggest reviewers or link an issue to this PR when I opened it. Is it a permissions issue for the repository? Or maybe I just missed the right buttons to click (I'm still learning these github workflows)

2024-12-09 03:26 UTC, navidcy commented
oh possibly you are correct!
I think I gave you repo rights now...

but generally, you can even say something like`hey @user1, @user2, could you review this please?`

2024-12-09 22:46 UTC, navidcy requested changes
@andrewbrown31, @greensh16:

I see at the bottom:

```
#### Authors

* **Andrew Brown**

    ARC Centre of Excellence for 21st Century Weather, University of Melbourne
    
    a.brown1@unimelb.edu.au

* **Samuel Green**

    ARC Centre of Excellence for 21st Century Weather & Climate Change Research Centre, UNSW Sydney
    
    sam.green@unsw.edu.au
```

May I suggest:

1. Change "Authors" to "Contributors"?
2. Remove the email addresses (but leave the affiliations). Having the email addresses there might urge people to contact individuals for bugs or if something doesn't seem to work.
3. Add a line along the spirit of "For any inquiries or if you stumble upon a bug with the current recipe please open [an issue](https://github.com/ACCESS-Community-Hub/atmosphere-cookbook/issues/new?template=Blank+issue) or [a discussion](https://github.com/ACCESS-Community-Hub/atmosphere-cookbook/discussions/new/choose) in the repository."

What do you think?

2024-12-09 22:55 UTC, andrewbrown31 commented
I'm happy to make these changes! I suppose this is a good time to think about what kind of statements we'd like to include (while the cookbook is still new), so also happy to hear suggestions from @greensh16

2024-12-09 23:07 UTC, navidcy commented
We can always also homogenise all recipes later btw. But yeah, keen to hear your thoughts about my suggestions. I was trying to find a middle ground that attribution is made but we somehow don't give out the sediment that this recipe belongs to these two people; it's a community effort and people should reach out via the repository for any inquiries, bug reports etc.

2024-12-09 23:13 UTC, greensh16 commented
Yep I'm happy with those changes too, definitely should add a sentence at the bottom to open an issue if there are problems/bugs.

2024-12-10 22:43 UTC, navidcy commented on Recipes/AUS2200_xarray_rolling.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #42.            fnames = "/g/data/ua8/AUS2200/"+exp_id+"/v1-0/"+freq+"/"+vname+"/"+vname+"_AUS2200_"+exp_id+"_*.nc"
</pre><p> </p><p>can we use the intake catalog here instead of explicitly prescribing a directory on wadi?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/ACCESS-Community-Hub/atmosphere-cookbook/pull/18/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='6'/>

2024-12-10 22:45 UTC, navidcy approved these changes
lgtm, great addition!

if we can avoid explicitly reading from gadi directories and use the intake catalog it'd be great; if not let's merge and we can deal with conversion to using the intake later

2024-12-10 22:45 UTC, andrewbrown31 commented on Recipes/AUS2200_xarray_rolling.ipynb
> +{
I tried to do this but had issues. See #20

2024-12-10 22:45 UTC, navidcy commented
@andrewbrown31 you should be able to merge; do that at will

2024-12-10 22:48 UTC, merged