Fix Issue #7: Changed logo to that of ACCESS Atmosphere WG
ACCESS-Community-Hub/atmosphere-cookbook pull request #9
Opened 2024-08-27 23:40 UTC by heidinett

Fixes Issue #7 - W21C logo replaced with that of ACCESS Atmosphere WG.

2024-08-27 23:43 UTC, navidcy commented
@angus-g why we don't see the docs previews here? Is it because we transferred the repo?

2024-08-27 23:49 UTC, navidcy commented on README.md
> +# Atmosphere Cookbook
should we rename the repo?

"Atmospheric" characterises the cookbook... that was my thinking

2024-08-27 23:53 UTC, heidinett commented on README.md
> +# Atmosphere Cookbook
Yes please @navidcy, that would be great if you could change it to "atmosphere-cookbook" instead of "atmospheric-cookbook"

2024-08-27 23:54 UTC, angus-g commented
> @angus-g why we don't see the docs previews here? Is it because we transferred the repo?

I see the preview, unless you're referring to something else?
![image](https://github.com/user-attachments/assets/42aaebfb-443b-445a-8e6f-394f9ea9591b)

2024-08-27 23:55 UTC, navidcy commented on README.md
> +# Atmosphere Cookbook
I can do that, but why not "atmospheric cookbook"? I think atmospheric is more correct grammatically but I'm also not a native English speaker...

2024-08-27 23:56 UTC, navidcy commented
> > @angus-g why we don't see the docs previews here? Is it because we transferred the repo?
> 
> I see the preview, unless you're referring to something else? ![image](https://private-user-images.githubusercontent.com/11085886/362025522-42aaebfb-443b-445a-8e6f-394f9ea9591b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MDMxODYsIm5iZiI6MTcyNDgwMjg4NiwicGF0aCI6Ii8xMTA4NTg4Ni8zNjIwMjU1MjItNDJhYWViZmItNDQzYi00NDVhLThlNmYtMzk0ZjllYTk1OTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDIzNTQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1OTQ1MWRiMTg3ZThhMmQyOTk3MzUwMmZjNzNmNjVjZWE5YTk0Y2U5ZTY5MjU5MzVhZGQ2ZmY4NjdmMDQ5MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.68J5bD_xM5dOpws2pUJzinjxLBYjOpadyqvXPG8BkD4)

I changed the repo settings in the readthedocs and it worked!

2024-08-27 23:58 UTC, navidcy commented
Let's converge on the name and then ensure that we change it everywhere (e.g. in the docs also).

2024-08-27 23:58 UTC, navidcy requested changes
Let's converge on the name and then ensure that we change it everywhere (e.g. in the docs also).

2024-08-28 00:11 UTC, heidinett commented on README.md
> +# Atmosphere Cookbook
I prefer "Atmosphere Cookbook" as it takes on the name of the Atmosphere community, I guess similar to the Cosima Cookbook for the Cosima community.

2024-08-28 10:28 UTC, heidinett commented
@navidcy - do we now have consensus on the name "atmosphere cookbook"? 
Would be great to merge this PR before the ACCESS workshop next week.

2024-08-29 01:19 UTC, navidcy commented on README.md
> +# Atmosphere Cookbook
Yeah let's do that if you prefer.

2024-08-29 01:19 UTC, navidcy commented on README.md
> +# Atmosphere Cookbook
We should change it in the docs and everywhere.

2024-08-29 01:51 UTC, heidinett commented
great. Thanks @navidcy!

2024-08-29 02:14 UTC, navidcy commented
There are a bunch of "atmospheric" at https://atmospheric-cookbook--9.org.readthedocs.build/en/9/

2024-08-29 02:31 UTC, heidinett commented
Would you prefer that I open a new issue to replace "atmospheric" with "atmosphere" in Readthedocs, or address it in this issue?

2024-08-29 04:29 UTC, navidcy commented
Let's address it here? Whatever suits you.

2024-08-29 04:30 UTC, navidcy approved these changes
lgtm!

feel free to merge @heidinett when you deal with "atmospheric" -> "atmosphere"

2024-08-29 05:18 UTC, heidinett commented
@navidcy, I have replaced references to "atmospheric" with "atmosphere" and created a COPYRIGHT.txt file.

2024-08-29 05:21 UTC, merged